### ISSUE TITLE
tcomparable_without_macro.h

### ISSUE THREAD

**Issue by HolgerDu** [ToshioCP/Gobject-tutorial#11]
Hello,

Thank you for the great tutorial. 
However, I found a problem at the very end. 

I had to change "tcomparable-without-macro.h" to compile it: 

```
#pragma once
#include<gtk/gtk.h>

#define T_TYPE_COMPARABLE  (t_comparable_get_type ())
//G_DECLARE_INTERFACE (TComparable, t_comparable, T, COMPARABLE, GObject)
#define T_COMPARABLE(instance)           (G_TYPE_CHECK_INSTANCE_CAST(instance, T_TYPE_COMPARABLE, TComparable))
#define T_IS_COMPARABLE(instance)        (G_TYPE_CHECK_INSTANCE_TYPE(instance, T_TYPE_COMPARABLE))
#define T_COMPARABLE_GET_IFACE(instance) (G_TYPE_INSTANCE_GET_INTERFACE((instance), T_TYPE_COMPARABLE, TComparableInterface))  //Supplement  !! //

typedef struct _TComparable TComparable;
typedef struct _TComparableInterface TComparableInterface;

struct _TComparableInterface {
  GTypeInterface parent;
  /* signal */
  void (*arg_error) (TComparable *self);
  /* virtual function */
  int (*cmp) (TComparable *self, TComparable *other);
};

/* t_comparable_cmp */
/* if self > other, then returns 1 */
/* if self = other, then returns 0 */
/* if self < other, then returns -1 */
/* if error happens, then returns -2 */

GType    t_comparable_get_type             (void) G_GNUC_CONST;

int
t_comparable_cmp (TComparable *self, TComparable *other);

```
Greetings

**Comment by ToshioCP** [comment]
Thank you very much for posting this issue.
I checked the program and found that the codes included bugs. And I didn't separate files with macro and files without macto. I checked all the files and the bug was fixed. Please see the files under `src/tcomparable/XXXX_without_macro` files.
If you find anything, feel free to post comments.
I will keep this issue for about a week, and if no further posting, I will close it.
Thank you again, and have fun in GTK programing.

Toshio Sekiya

**Comment by HolgerDu** [comment]
Unfortunately, there is still a bug in the "comarable_without_macro.h".   
It must say: 
```
#define T_COMPARABLE_GET_IFACE(instance) (G_TYPE_INSTANCE_GET_INTERFACE((instance), T_TYPE_COMPARABLE, TComparableInterface))  
```
Probably it did not notice because the file "comparable_without_macro.c" is not referenced to "comparable_without_macro.h".  

Greetings 

Holger

**Comment by ToshioCP** [comment]
Thank you very much.
The bug has been fixed.

Toshio Sekiya
