### ISSUE TITLE
typo in sec6

### ISSUE THREAD

**Issue by cedric-sun** [ToshioCP/Gobject-tutorial#3]
https://github.com/ToshioCP/Gobject-tutorial/blob/main/gfm/sec6.md?plain=1#L39

> When an instance is TNumber type, it is an instance of TInt or TDouble as well.

should be

> When an instance is of TInt or TDouble type, it is an instance of TNumber as well.

btw. I appreciate your work! IMHO, It's way better organized than [gobject's official guide](https://docs.gtk.org/gobject/tutorial.html).

**Comment by ToshioCP** [comment]
Hello, cedric-sun.
Thank you for posting the issue.
I will 'git push' soon because of the update for Rakefile and the files under the 'lib' directory.
And I'm going to fix this issue in the same commit.
So, wait a while until then.
Thank you again for your cooperation.

Toshio Sekiya

**Comment by ToshioCP** [comment]
The sentence is corrected.
This issue will be closed.
Thank you, cedric-sun.
