### ISSUE TITLE
Typo in section 4

### ISSUE THREAD

**Issue by Gwarek2** [ToshioCP/Gobject-tutorial#4]
https://github.com/ToshioCP/Gobject-tutorial/blob/main/gfm/sec4.md?plain=1#L104
https://github.com/ToshioCP/Gobject-tutorial/blob/main/gfm/sec4.md?plain=1#L110
> ```void dev_by_zero_cb (TDouble *d, gpointer user_data) { ... ... ...};```

and

> ```void dev_by_zero_cb (TDouble *d) { ... ... ...};```

should be

> ```void div_by_zero_cb (TDouble *d, gpointer user_data) { ... ... ...};```

and

> ```void div_by_zero_cb (TDouble *d) { ... ... ...};```

**Comment by ToshioCP** [comment]
Thak you for the post, Fedor.
I've fixed the typo errors.

Toshio Sekiya
