### ISSUE TITLE
The documentation does not say what GObject "IS"

### ISSUE THREAD

**Issue by gdennie** [ToshioCP/Gobject-tutorial#9]
The documentation seems to only talk about how to use GObject and not what it is used for. It is a simple thing that demands research from casual readers trying to find footing. Two sentences should be sufficient.

**Comment by ToshioCP** [comment]
Hi, George,

Thank you for posting the issue.
It is difficult to say what GObject is.
It is similar to explain Object-Oriented.

But I think it is important to point out the relation between GObject and GTK.
GTK is the GUI system for GNOME and many applications.
GObject is the base system for GTK.

I changed the `Readme.md` and add them to it.
I think the update may be the resolution for the issue more or less.

Toshio Sekiya

**Comment by EmVee381** [comment]
> The documentation seems to only talk about how to use GObject and not what it is used for. It is a simple thing that demands research from casual readers trying to find footing. Two sentences should be sufficient.

btw. it is best to read tutorial and watch definitions in header files :) so far :) btw. @ToshioCP thank you, it really helps
